Deliverables for sprint05 release candidate
amosproj/amos2023ws06-sales-lead-qualifier pull request #120
Opened 2023-11-29 07:11 UTC by ur-tech

2023-11-29 08:57 UTC, NicoHambauer commented
Hey there! Looks good.
However, do we also need the current planning document pdf? And did the planning document change this sprint?

@ur-tech 

Thanks for creating this one.

2023-11-29 08:58 UTC, NicoHambauer requested changes
Looks good, but i am missing the planning document.
Correct me if I am wrong.

2023-12-02 12:12 UTC, Tims777 approved these changes

2023-12-02 12:17 UTC, NicoHambauer approved these changes
Looks good! Really nice that you create and uploaded a nice Build process Video!! Well done!

2023-12-02 12:18 UTC, merged