Feature/174 use default pipeline during sprint release
amosproj/amos2023ws06-sales-lead-qualifier pull request #183
Opened 2024-01-01 22:36 UTC by rbbozkurt

- Added support for starting pipeline from predefined config files in `.json` format.
- refactored some pipeline and console related implementations.

2024-01-04 16:58 UTC, felix-zailskas requested changes
Good Job on cleaning up! I think this is very well manageable and easy to understand. 

However, I have found the following bugs while testing
1. Not listing the available configs seems to create an error.
```
(1) BDC
(2) EVP
(3) DB
(4) Pipeline
(5) Exit
4
Do you want to list all available pipeline configs? (y/N)
n
Set limit for data points to be processed (0=No limit)
0
Traceback (most recent call last):
  File "/Users/felixzailskas/Code/amos2023ws06-sales-lead-qualifier/src/main.py", line 28, in <module>
    pipeline_demo()
  File "/Users/felixzailskas/Code/amos2023ws06-sales-lead-qualifier/src/demo/demos.py", line 183, in pipeline_demo
    steps_info = "\n".join([str(step) for step in steps])
UnboundLocalError: local variable 'steps' referenced before assignment
```

2. When listing the available pipeline configs and then moving to the custom one it always says invalid choice on the phone number step.
```
(1) BDC
(2) EVP
(3) DB
(4) Pipeline
(5) Exit
4
Do you want to list all available pipeline configs? (y/N)
y
Please enter the index of requested pipeline config:
(0) : run_all_steps.json 
(1) : Exit 
1
Exiting...

Continuing with custom pipeline config...


Run Scrape Address (will take a long time)(y/N)?
n
Run Facebook Graph API (will use token)(y/N)?
n
Run Phone Number Validation (y/N)?
n
Invalid choice
(1) BDC
(2) EVP
(3) DB
(4) Pipeline
(5) Exit
```

2024-01-06 12:10 UTC, rbbozkurt commented
>     1. Not listing the available configs seems to create an error.
> 
> 
> (1) BDC
> (2) EVP
> (3) DB
> (4) Pipeline
> (5) Exit
> 4
> Do you want to list all available pipeline configs? (y/N)
> n
> Set limit for data points to be processed (0=No limit)
> 0
> Traceback (most recent call last):
>   File "/Users/felixzailskas/Code/amos2023ws06-sales-lead-qualifier/src/main.py", line 28, in <module>
>     pipeline_demo()
>   File "/Users/felixzailskas/Code/amos2023ws06-sales-lead-qualifier/src/demo/demos.py", line 183, in pipeline_demo
>     steps_info = "\n".join([str(step) for step in steps])
> UnboundLocalError: local variable 'steps' referenced before assignment
> ```
The bug was reproducable and succesfully fixed.

2024-01-06 12:36 UTC, rbbozkurt commented
>     2. When listing the available pipeline configs and then moving to the custom one it always says invalid choice on the phone number step.
> 
>
> (1) BDC
> (2) EVP
> (3) DB
> (4) Pipeline
> (5) Exit
> 4
> Do you want to list all available pipeline configs? (y/N)
> y
> Please enter the index of requested pipeline config:
> (0) : run_all_steps.json 
> (1) : Exit 
> 1
> Exiting...
> 
> Continuing with custom pipeline config...
> 
> 
> Run Scrape Address (will take a long time)(y/N)?
> n
> Run Facebook Graph API (will use token)(y/N)?
> n
> Run Phone Number Validation (y/N)?
> n
> Invalid choice
> (1) BDC
> (2) EVP
> (3) DB
> (4) Pipeline
> (5) Exit
> ```

The bug was reproducable and fixed.

2024-01-09 11:22 UTC, felix-zailskas approved these changes

2024-01-09 17:41 UTC, merged