Last sprint's deliverables
amosproj/amos2023ws06-sales-lead-qualifier pull request #237
Opened 2024-02-04 18:50 UTC by ultiwinter

Last sprint's deliverables
- User documentation
- Design documentation
- Build documentation
- Planning documentation

2024-02-05 20:43 UTC, Tims777 commented on Documentation/Classifier-Comparison.md
> +In summary, XGBoost consistently demonstrated superior performance, showcasing robust results across various splits and subsets. However, it is crucial to note that its elevated score is attributed t
Nice summary.

2024-02-05 21:02 UTC, Tims777 requested changes
Good work overall. Please just provide me with the source files of the compiled PDFs, because I would like to update the underlying Wiki.

2024-02-06 11:25 UTC, Tims777 commented on Deliverables/sprint-13/build-documentation.pdf
Done.

2024-02-06 11:25 UTC, Tims777 commented on Deliverables/sprint-13/planning-documents.pdf
Done.

2024-02-06 23:07 UTC, Tims777 commented on Deliverables/sprint-13/build-documentation.pdf
Felix created an updated version, which I just uploaded.

2024-02-06 23:08 UTC, Tims777 commented on Deliverables/sprint-13/user-documentation.pdf
Using the files you provided, I was able to do some minor adjustments. Thanks!

2024-02-06 23:09 UTC, Tims777 commented on Deliverables/sprint-13/design-documentation.pdf
I merged Architecture.md into the design documentation, so we do now also have the Component Diagram in there.

2024-02-06 23:09 UTC, Tims777 approved these changes

2024-02-07 00:42 UTC, ur-tech approved these changes

2024-02-07 00:42 UTC, ur-tech commented on Documentation/User-Documentation.md
Very nice overview

2024-02-07 09:20 UTC, merged